name: lahazaat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  app_settings: ^4.1.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.9.1
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  internet_connection_checker: ^0.0.1+4
  permission_handler: ^10.0.0
  timezone: ^0.8.0
  url_launcher: ^6.1.5
  neat_periodic_task: ^2.0.0
  flutter_inappwebview: ^5.4.3+7
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter
  rename: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
